// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SistemaMottuAPI.Data;

#nullable disable

namespace SistemaMottuAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250524183638_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaMottuAPI.Model.Camera", b =>
                {
                    b.Property<int>("IdCamera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CAMERA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCamera"));

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LOCALIZACAO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'ativo'");

                    b.Property<DateTime>("UltimaVerificacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ULTIMA_VERIFICACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("IdCamera");

                    b.ToTable("CAMERAS", (string)null);
                });

            modelBuilder.Entity("SistemaMottuAPI.Model.Cargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CARGO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCargo"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("NivelPermissao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NIVEL_PERMISSAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NOME");

                    b.Property<string>("Permissoes")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("PERMISSOES");

                    b.HasKey("IdCargo");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("CARGOS", null, t =>
                        {
                            t.HasCheckConstraint("CK_CARGO_NIVEL", "NIVEL_PERMISSAO BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("SistemaMottuAPI.Model.LogAlteracao", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LOG");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<string>("CampoAlterado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CAMPO_ALTERADO");

                    b.Property<DateTime>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdMoto")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MOTO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("TipoAcao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("TIPO_ACAO");

                    b.Property<string>("ValorAntigo")
                        .HasColumnType("CLOB")
                        .HasColumnName("VALOR_ANTIGO");

                    b.Property<string>("ValorNovo")
                        .HasColumnType("CLOB")
                        .HasColumnName("VALOR_NOVO");

                    b.HasKey("IdLog");

                    b.HasIndex("IdMoto");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("TipoAcao")
                        .HasDatabaseName("IDX_LOG_ACAO");

                    b.ToTable("LOG_ALTERACOES", (string)null);
                });

            modelBuilder.Entity("SistemaMottuAPI.Model.Moto", b =>
                {
                    b.Property<int>("IdMoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MOTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMoto"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("COR");

                    b.Property<string>("ImagemReferencia")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("IMAGEM_REFERENCIA");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MARCA");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("NVARCHAR2(7)")
                        .HasColumnName("PLACA");

                    b.Property<string>("Presente")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasColumnName("PRESENTE")
                        .HasDefaultValueSql("'Não'");

                    b.HasKey("IdMoto");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("MOTOS", (string)null);
                });

            modelBuilder.Entity("SistemaMottuAPI.Model.Reconhecimento", b =>
                {
                    b.Property<int>("IdReconhecimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RECONHECIMENTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReconhecimento"));

                    b.Property<decimal>("ConfiancaMinima")
                        .HasPrecision(5, 4)
                        .HasColumnType("DECIMAL(5,4)")
                        .HasColumnName("CONFIANCA_MINIMA");

                    b.Property<DateTime>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdCamera")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CAMERA");

                    b.Property<int>("IdMoto")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MOTO");

                    b.Property<string>("ImagemCapturada")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("IMAGEM_CAPTURADA");

                    b.Property<decimal>("Precisao")
                        .HasPrecision(5, 4)
                        .HasColumnType("DECIMAL(5,4)")
                        .HasColumnName("PRECISAO");

                    b.HasKey("IdReconhecimento");

                    b.HasIndex("DataHora")
                        .HasDatabaseName("IDX_RECONHECIMENTO_DATA");

                    b.HasIndex("IdCamera");

                    b.HasIndex("IdMoto");

                    b.ToTable("RECONHECIMENTOS", (string)null);
                });

            modelBuilder.Entity("SistemaMottuAPI.Model.Registro", b =>
                {
                    b.Property<int>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGISTRO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegistro"));

                    b.Property<DateTime>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdMoto")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MOTO");

                    b.Property<int?>("IdReconhecimento")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RECONHECIMENTO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("ModoRegistro")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("MODO_REGISTRO");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("TIPO");

                    b.HasKey("IdRegistro");

                    b.HasIndex("IdMoto");

                    b.HasIndex("IdReconhecimento");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("IDX_REGISTRO_TIPO");

                    b.ToTable("REGISTROS", (string)null);
                });

            modelBuilder.Entity("SistemaMottuAPI.Model.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasColumnName("ATIVO")
                        .HasDefaultValueSql("'Sim'");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<int>("IdCargo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CARGO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("SENHA");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdCargo");

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("SistemaMottuAPI.Model.LogAlteracao", b =>
                {
                    b.HasOne("SistemaMottuAPI.Model.Moto", "Moto")
                        .WithMany("LogsAlteracoes")
                        .HasForeignKey("IdMoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LOG_MOTO");

                    b.HasOne("SistemaMottuAPI.Model.Usuario", "Usuario")
                        .WithMany("LogsAlteracoes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LOG_USUARIO");

                    b.Navigation("Moto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaMottuAPI.Model.Reconhecimento", b =>
                {
                    b.HasOne("SistemaMottuAPI.Model.Camera", "Camera")
                        .WithMany("Reconhecimentos")
                        .HasForeignKey("IdCamera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_REC_CAMERA");

                    b.HasOne("SistemaMottuAPI.Model.Moto", "Moto")
                        .WithMany("Reconhecimentos")
                        .HasForeignKey("IdMoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_REC_MOTO");

                    b.Navigation("Camera");

                    b.Navigation("Moto");
                });

            modelBuilder.Entity("SistemaMottuAPI.Model.Registro", b =>
                {
                    b.HasOne("SistemaMottuAPI.Model.Moto", "Moto")
                        .WithMany("Registros")
                        .HasForeignKey("IdMoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_REG_MOTO");

                    b.HasOne("SistemaMottuAPI.Model.Reconhecimento", "Reconhecimento")
                        .WithMany("Registros")
                        .HasForeignKey("IdReconhecimento")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_REG_RECONHECIMENTO");

                    b.HasOne("SistemaMottuAPI.Model.Usuario", "Usuario")
                        .WithMany("Registros")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_REG_USUARIO");

                    b.Navigation("Moto");

                    b.Navigation("Reconhecimento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaMottuAPI.Model.Usuario", b =>
                {
                    b.HasOne("SistemaMottuAPI.Model.Cargo", "Cargo")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USUARIO_CARGO");

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("SistemaMottuAPI.Model.Camera", b =>
                {
                    b.Navigation("Reconhecimentos");
                });

            modelBuilder.Entity("SistemaMottuAPI.Model.Cargo", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaMottuAPI.Model.Moto", b =>
                {
                    b.Navigation("LogsAlteracoes");

                    b.Navigation("Reconhecimentos");

                    b.Navigation("Registros");
                });

            modelBuilder.Entity("SistemaMottuAPI.Model.Reconhecimento", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("SistemaMottuAPI.Model.Usuario", b =>
                {
                    b.Navigation("LogsAlteracoes");

                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
